quezemasterNew/Models/ViewModel/ResultDetailsViewModel.cs
namespace quezemasterNew.Models.ViewModel
{
    public class ResultDetailsViewModel
    {
        public int SRNumber { get; set; } = 0;
        public string Name { get; set; } = "";
            public string Data { get; set; } = "";
        public string Question { get; set; } = "";
            public string AnsswerA { get; set; } = "";
        public string AnsswerB { get; set; } = "";
            public string AnsswerC { get; set; } = "";
        public string AnsswerD { get; set; } = "";
        public string AnsswerE { get; set; } = "";
            public string CurrectAnsawer { get; set; } = "";
        public int TotalCurrectAnswer { get; set; } = 0;
        
    }
}

quezemasterNew/Controllers/Class12Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using quezemasterNew.CommonFunctional;
using quezemasterNew.Models.Class9;
using quezemasterNew.Models.ViewModel.Test;
using quezemasterNew.Models.ViewModel;
using quezemasterNew.Models;
using System.Data;
using quezemasterNew.BussinesLogic;
using System.Threading.Tasks;

namespace quezemasterNew.Controllers
{
    public class Class12Controller : Controller
    {
        Class12Helper _Class12Helper= new Class12Helper();

        public async Task<IActionResult> Index(string Subject)
        {

            List<Class9ViewModel> LsClass12Details = new List<Class9ViewModel>();

            LsClass12Details = await _Class12Helper.FillClass12QuizDetailsBySubjectName(LsClass12Details: LsClass12Details, Subject: Subject);

            return View(LsClass12Details);
        }

        public IActionResult Create()
        {

            return View();
        }

        public async Task<IActionResult> InsertClass12(Class9ViewModel data)
        {

            try
            {

                if (data != null)
                {
                    await _Class12Helper.SaveClass12QuizDetails(data: data);
                }
             
            }
            catch (Exception ex)
            {


            }

            return RedirectToAction("Index", new { Subject  = data.SubjectName });
        }


        public async Task<IActionResult> AddQuestion(int id, int PrimaryId)
        {
            QuestionPepar10ViewModel Class12PaperDetails = new QuestionPepar10ViewModel();

            try
            {

                Class12PaperDetails.ConnectedQuestion = id;
                if (PrimaryId > 0)
                {
                 
                    await _Class12Helper.FillQuestionPaperClaass12Details(Class12PaperDetails: Class12PaperDetails, PrimaryId: PrimaryId);

                }


                Class12PaperDetails.lsListQuestion = new List<QuestionPepar10ViewModel>();

                Class12PaperDetails.lsListQuestion = await _Class12Helper.FillQuestionpaperClass12DetailsById(LsQuestionDetais: Class12PaperDetails.lsListQuestion, Id: id);

            }
            catch (Exception ex)
            {

            }

            return View(Class12PaperDetails);

        }

        public async Task<IActionResult> QuestionAddForm20Details(QuestionPepar10ViewModel data)
        {
            try
            {


                if (data.PrimaryId == 0)
                {
                    if (data.QuestionNo != null)
                    {

                        await _Class12Helper.SavetblQuestionPeparEnglishClass12Details(QuestionDetails: data);

                    }
                }
                else
                {

                    await _Class12Helper.UpdatetblQuestionPeparEnglishClass12Details(PrimaryId: data.PrimaryId, QuestionDetails: data);


                }
            }
            catch (Exception ex)
            {

            }

            return RedirectToAction("AddQuestion", new { id = data.ConnectedQuestion });
        }

        public async Task<IActionResult> DeleteQuestion(int id, int ConnectionId)
        {
            try
            {

                if (id > 0)
                {
                    await _Class12Helper.DeletetblQuestionPeparEnglishClass12Details(PrimaryId: id);
                }
            
            }
            catch (Exception EX)
            {
            }
            return RedirectToAction("AddQuestion", new { id = ConnectionId });
        }


        public async Task<IActionResult> DeleteTest(int id,string Subject)
        {
            try
            {

                if (id > 0)
                {
                    await _Class12Helper.DeletetblQuezIndexClass12Details(PrimaryId: id);
                }

            }
            catch (Exception EX)
            {
            }
            return RedirectToAction("Index", new { Subject = Subject });
        }



        public async Task<IActionResult> TestOnline(string SubjectName)
        {

            List<Class9QuestionSetViewModel> LsClass12Details = new List<Class9QuestionSetViewModel>();

            try
            {
                if(!string.IsNullOrEmpty(SubjectName))
                {
                    LsClass12Details = await _Class12Helper.FillClass12QuestionSetDetailsBySubjectName(LsClass12Details: LsClass12Details, SubjectName: SubjectName);
                }
            }
            catch(Exception ex)
            {

            }

  

            return View(LsClass12Details);
        }

        public async Task<IActionResult> OnlineTest(int id, Test10DetailsViewModel test11)
        {

            int testa = 0;
            if (id == 0)
            {
                id = test11.ConnectionQuestion;
                testa = test11.TestId + 1;
            }

            try
            {
                if (test11.TestId != 0)
                {


                    TblClass12EnglisgTestFinalDetail finalResute = new TblClass12EnglisgTestFinalDetail();


                    finalResute.QuestionNo = test11.QuestionNo;

                    if (string.IsNullOrEmpty(test11.Answer) == false)
                    {
                        string[] Answer = test11.Answer.ToString().Split('-');
                        if (Answer.Length == 2)
                        {
                            if (Answer[0] == "A")
                            {
                                finalResute.AnswerA = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "B")
                            {
                                finalResute.AnswerB = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "C")
                            {
                                finalResute.AnswerC = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "D")
                            {
                                finalResute.AnswerD = Answer[1].ToString().Trim();
                            }
                        }
                    }

                    if (String.IsNullOrEmpty(finalResute.AnswerA) == false)
                    {
                        if (finalResute.AnswerA == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerB) == false))
                    {
                        if (finalResute.AnswerB == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerC) == false))
                    {
                        if (finalResute.AnswerC == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerD) == false))
                    {
                        if (finalResute.AnswerD == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }

                    finalResute.ConnectedQuestion = test11.ConnectionQuestion;

                    var currentuser = User.Identity.Name;
                    if (string.IsNullOrEmpty(currentuser) == false)
                    {
                        finalResute.CurrentUser = currentuser;
                    }
                    else
                    {
                        finalResute.CurrentUser = "Na";
                    }


                    finalResute.TestQuestionId = test11.TestId;
                    finalResute.DatetimeStamp = DateTime.Now;

                    if (String.IsNullOrEmpty(finalResute.CurrentUser) == true)
                    {
                        finalResute.CurrentUser = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerA) == true)
                    {
                        finalResute.AnswerA = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerB) == true)
                    {
                        finalResute.AnswerB = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerC) == true)
                    {
                        finalResute.AnswerC = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerD) == true)
                    {
                        finalResute.AnswerD = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.QuestionNo) == true)
                    {
                        finalResute.QuestionNo = "";
                    }

                    if (String.IsNullOrEmpty(finalResute.CurrectAnswer) == true)
                    {
                        finalResute.CurrectAnswer = "";
                    }

                    if (String.IsNullOrEmpty(finalResute.TestSerise) == true)
                    {
                        finalResute.TestSerise = "";
                    }

                    finalResute.Remark = "";
                    finalResute.Remark1 = "";
                    finalResute.Remark2 = "";
                    finalResute.Remark3 = "";
                    finalResute.Remark4 = "";


                    await _Class12Helper.SavetblClass12EnglisgTestFinalDetails(finalResute: finalResute);
                

                    id = test11.ConnectionQuestion;
                    testa = test11.TestId + 1;
                }

               

quezemasterNew/Views/Class12/AddQuestion.cshtml
@model quezemasterNew.Models.ViewModel.QuestionPepar10ViewModel
@{
    ViewData["Title"] = "Add Question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #dataTable_filter, #dataTable_length, #dataTable_info, #dataTable_paginate {
        display: block;
        border: 1px solid black;
    }

    .table {
        border: 1px solid black;
    }

        .table thead th {
            border-bottom: 1px solid black;
        }

    button.dt-button, div.dt-button, a.dt-button, input.dt-button {
        background-color: #EC6BAB;
        color: white;
    }
</style>
<script>
    var $jq = jQuery.noConflict();
    $jq(document).ready(function () {
        var printCounter = 0;
        $jq('#ConfirmTable').DataTable({
            dom: 'Bfrtip',
            buttons: [

                {
                    extend: 'excel',
                    messageTop: 'Quize Index'
                },

                {
                    extend: 'print',
                    messageTop: function () {
                        printCounter++;

                        if (printCounter === 1) {
                            return '<center><h3><u>Quize Master</u></h3></center><hr/>';
                        }
                        else {
                            return '<center><h3><u>Quize Master</u></h3></center><hr/>';
                        }
                    },
                    messageBottom: null
                }
            ]
        });
    });
</script>
<br />
<form asp-action="QuestionAddForm20Details" asp-controller="Class12">
    <div class="row">
        <div class="col-md-1"></div>
        <input type="hidden" asp-for="ConnectedQuestion" />
        <input type="hidden" asp-for="PrimaryId" />
        <div class="col-md-10">
            <div class="card card-body">
                <h5 class="text-center"> Question Add</h5>
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        <label><strong>Question</strong></label>
                    </div>
                    <div class="col-md-8">
                        <input type="text" asp-for="QuestionNo" class="form-control" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        <label><strong>Answer A</strong></label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" asp-for="AnswerA" class="form-control" />
                    </div>
                    <div class="col-md-2">
                        <label><strong>Answer B</strong></label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" asp-for="AnswerB" class="form-control" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        <label><strong>Answer C</strong></label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" asp-for="AnswerC" class="form-control" />
                    </div>
                    <div class="col-md-2">
                        <label><strong>Answer D</strong></label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" asp-for="AnswerD" class="form-control" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        <label><strong>Currect Answer</strong></label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" asp-for="CurrectAnswer" class="form-control" />
                    </div>
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-4">
                        <input type="submit" value="Submit" class="btn btn-primary" style="background-color:#BC3578;" />
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-1"></div>
    </div>

</form>

<br />
<br />
<did>
    <table id="ConfirmTable" class="table table-bordered table-hover text-center" border="1">
        @{
            <thead class="text-white" style="background-color:#b66c9d">
                <tr>
                    <th>
                        <label><strong>Sr No</strong></label>
                    </th>
                    <th>
                        <label><strong>Question</strong></label>
                    </th>
                    <th>
                        <label><strong>Answer A</strong></label>
                    </th>
                    <th>
                        <label><strong>Answer B</strong></label>
                    </th>
                    <th>
                        <label><strong>Answer C</strong></label>
                    </th>
                    <th>
                        <label><strong>Answer D</strong></label>
                    </th>
                    <th>
                        <label><strong>Currect Answer</strong></label>
                    </th>


                    <th>Action</th>
                </tr>
            </thead>
            var i = 1;
            <tbody>
                @foreach (var item in Model.lsListQuestion)
                {
                    <tr>

                        <td data-label="Sr No">@Html.Label("" + i++.ToString())</td>
                        <td data-label="Question No">@item.QuestionNo </td>
                        <td data-label="Answer A"> @item.AnswerA</td>
                        <td data-label="Answer B"> @item.AnswerB</td>
                        <td data-label="Answer C"> @item.AnswerC</td>
                        <td data-label="Answer D"> @item.AnswerD</td>
                        <td data-label="Currect Answer"> @item.CurrectAnswer</td>
                        <td data-label="Action">

                            <a asp-action="AddQuestion" class="btn btn-success"
                               asp-route-PrimaryId="@item.Id" asp-route-id="@item.ConnectedQuestion" asp-controller="Class12">Edit</a>
                            <a asp-action="DeleteQuestion" class="btn btn-danger"
                               asp-route-id="@item.Id" asp-route-ConnectionId="@item.ConnectedQuestion" asp-controller="Class12">Delete</a>
                        </td>

                    </tr>
                }
            </tbody>
        }
    </table>
</did>

quezemasterNew/Views/Class12/Create.cshtml
@model quezemasterNew.Models.Class9.Class9ViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 card card-body">
        <form asp-action="InsertClass12" asp-controller="Class12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="QuezName" class="control-label"></label>
                <input asp-for="QuezName" class="form-control" />
                <span asp-validation-for="QuezName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassName" class="control-label"></label>
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectName" class="control-label"></label>
                <select class="form-select" asp-for="SubjectName">
                    <option value="English">English</option>
                    <option value="Hindi">Hindi</option>
                    <option value="History">History</option>
                </select>
                @* <input asp-for="SubjectName" class="form-control" /> *@
                <span asp-validation-for="SubjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remark" class="control-label"></label>
                <input asp-for="Remark" class="form-control" />
                <span asp-validation-for="Remark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="TGTIndex">Back to List</a>
        </div>
    </div>
</div>

quezemasterNew/Views/Class12/OnlineTest.cshtml
@{
    ViewData["Title"] = "Test";
}

@model quezemasterNew.Models.ViewModel.Test.Test10DetailsViewModel
<style>
    input, button, select, optgroup, textarea {
        margin-top: 1;
        font-family: inherit;
        font-size: inherit;
        line-height: inherit;
        height: 20px;
        width: 20px;
    }
</style>

@ViewBag.Message

<div class="container">
    <form asp-action="OnlineTest" asp-controller="Class12">
        <div class="row" style="font-weight:16px">
            <div class="col-md-1"></div>
            <div class="col-md-10" style="padding-top:100px">
                <div class="row">
                    <div class="card card-body" style="border:1px solid grey;border-radius:5px">
                        <input type="hidden" asp-for="@Model.TestId" />
                        <input type="hidden" asp-for="ConnectionQuestion" />
                        <input type="hidden" asp-for="QuestionId" />
                        <input type="hidden" asp-for="FinalTest" />
                        <input type="hidden" asp-for="CurrectAnswer" />
                        <input type="hidden" asp-for="QuestionNo" />
                        <input type="hidden" asp-for="QuizName" />
                        <h4 class="text-center">Quiz Name - @Model.QuizName</h4>
                        <hr />

                        <div class="row">
                            <h4>Q. - @Model.QuestionNo</h4>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-4">
                                <h4>@Html.RadioButton("Answer", "A-" + @Model.AnswerA, Model.AnswerA == "A") @Model.AnswerA</h4>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-4">
                                <h4>@Html.RadioButton("Answer", "B-" + @Model.AnswerB, Model.AnswerB == "B")  @Model.AnswerB</h4>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-4">
                                <h4>@Html.RadioButton("Answer", "C-" + @Model.AnswerC, Model.AnswerC == "C")  @Model.AnswerC </h4>

                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-4">

                                <h4> @Html.RadioButton("Answer", "D-" + @Model.AnswerD, Model.AnswerD == "D")  @Model.AnswerD </h4>
                            </div>
                        </div>
                        <br />
                        <br />
                        <br />
                        <div class="row">
                            <div class="col-md-4"></div>

                            @if (Model.FinalTest == "Final Test")
                            {
                                <div class="col-md-4">
                                    <input type="submit" value="Submit" class="btn btn-success" style="width:200px;height:50px" />
                                </div>
                            }
                            else
                            {
                                <div class="col-md-4">
                                    <input type="submit" value="Next" class="btn btn-primary" style="width:200px;height:50px;" />
                                </div>
                            }

                            <div class="col-md-2"></div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </form>
</div>

quezemasterNew/Views/Class12/TestOnline.cshtml
@model IEnumerable<quezemasterNew.Models.Class9.Class9QuestionSetViewModel>

    <title>TGT Test</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
    a5:visited, a.ex5:link {
        text-decoration: none;
    }

    a.ex5:hover, a.ex5:active {
        text-decoration: underline;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="w3-panel w3-card" style="border-radius:20px">
                <div class="col-md-1" style="padding-top:0px">
                    <img src="~/image\notes-removebg-preview.png" height="0px" width="0px" style="padding-left:0px" />
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table-responsive-lg">
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <p style="font-size:17px;color:black;padding-top:10px">
                                            <a class="ex5" asp-action="OnlineTest" asp-controller="Class12" asp-route-id="@item.id" style="padding-left:0px;font-size:17px;color:black;font-weight:400;padding-top:10px">@item.QuestionSetName</a>
                                        </p>
                                        <h5 style="color:#4CBB17;font-weight:400">
                                            Question : 20 &nbsp; &nbsp;&nbsp <i class="fa fa-clock-o" style="font-size:12px;color:#4CBB17;font-weight:500"></i> 30 Minutes
                                        </h5>
                                        <hr />

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>


        <div class="col-md-4">

            <br />
            <br />
            <br />
            <div class="w3-panel w3-card" style="border-radius:10px">
                <div class="w3-panel w3-card" style="border-radius:5px;background-color:#f4f4f4">
                    <center>
                        <h5 style="font-weight:400">Quick links</h5>
                    </center>
                </div>

                <h5 style="color:#4CBB17;font-weight:600;padding-top:50px">
                    Quantitative Aptitude
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:20px;font-size:20px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">Arithmetic</a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:20px;font-size:20px;color:gray;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">Data Interpretation</a>
                </h5>



                <h5 style="color:#4CBB17;font-weight:600">
                    Verbal (English)
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:19px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Verbal Ability
                    </a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:19px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Verbal Test
                    </a>
                </h5>

                <h5 style="color:#4CBB17;font-weight:600">
                    Reasoning
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Logical

                    </a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Verbal
                    </a>
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Nonverbal
                    </a>
                </h5>

                <h5 style="color:#4CBB17;font-weight:600">
                    Programming
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        C  Programming

                    </a>
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        C++
                    </a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Java
                    </a>
                </h5>

                <h5 style="color:#4CBB17;font-weight:600">
                    Interview
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        GD
                    </a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        HR
                    </a>
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Technical Interview
                    </a>
                </h5>


                <h5 style="color:#4CBB17;font-weight:600">
                    Placement Papers
                </h5>


                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:gray;padding:7px;padding-top:8px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Placement Papers
                    </a>
                </h5>

                <h5 style="font-size:17px;color:gray">
                    <i style="padding-left:12px;font-size:17px;color:black;padding:8px;padding-top:3px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" style="font-weight:500">
                        Submit Paper
                    </a>
                </h5>
            </div>
        </div>

    </div>
</div>