quezemasterNew/Controllers/Class6Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using quezemasterNew.CommonFunctional;
using quezemasterNew.Models.Class9;
using quezemasterNew.Models.ViewModel.Test;
using quezemasterNew.Models.ViewModel;
using quezemasterNew.Models;
using System.Data;
using quezemasterNew.BussinesLogic;

namespace quezemasterNew.Controllers
{
    public class Class6Controller : Controller
    {
        QuizeMasterNewContext _context = new QuizeMasterNewContext();
        Class6Helper _Class6Helper =new Class6Helper();
        public async Task<IActionResult> Index(string Subject)
        {

            List<Class9ViewModel> LsClass6QuezDetails = new List<Class9ViewModel>();
            LsClass6QuezDetails = await _Class6Helper.FillClass6QuizDetailsBySubjectName(LsClass6QuezDetails: LsClass6QuezDetails, Subject: Subject);

            return View(LsClass6QuezDetails);
        }

        public IActionResult Create()
        {

            return View();
        }

        public async Task<IActionResult> InsertClass6(Class9ViewModel data)
        {
            try
            {
                if(data!=null)
                {
                    await _Class6Helper.SaveClass6QuizDetails(data: data);
                }
            }
            catch (Exception ex)
            {
            }

    

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> AddQuestion(int id, int PrimaryId)
        {
            QuestionPepar10ViewModel Class6PaperDetails = new QuestionPepar10ViewModel();

            try
            {

                Class6PaperDetails.ConnectedQuestion = id;
                if (PrimaryId > 0)
                {
              
                    await _Class6Helper.FillQuestionPaperClaass6Details(Class6PaperDetails: Class6PaperDetails, PrimaryId: PrimaryId);
                }


                Class6PaperDetails.lsListQuestion = new List<QuestionPepar10ViewModel>();


                Class6PaperDetails.lsListQuestion = await _Class6Helper.FillQuestionpaperClass6DetailsById(LsQuestionDetais: Class6PaperDetails.lsListQuestion, Id: id);

            }
            catch (Exception ex)
            {

            }

            return View(Class6PaperDetails);

        }

        public async Task<IActionResult> QuestionAddForm20Details(QuestionPepar10ViewModel data)
        {
            try
            {


                if (data.PrimaryId == 0)
                {
                    if (data.QuestionNo != null)
                    {

                        await _Class6Helper.SavetblQuestionPeparEnglishClass6Details(QuestionDetails: data);

                    }
                }
                else
                {


                    await _Class6Helper.UpdatetblQuestionPeparEnglishClass6Details(PrimaryId: data.PrimaryId, QuestionDetails: data);

                }
            }
            catch (Exception ex)
            {

            }

            return RedirectToAction("AddQuestion", new { id = data.ConnectedQuestion });
        }

        public  async Task<IActionResult> DeleteQuestionAsync(int id, int ConnectionId)
        {
            try
            {

                await _Class6Helper.DeletetblQuestionPeparEnglishClass6Details(PrimaryId: id);

            }
            catch (Exception EX)
            {
            }
            return RedirectToAction("AddQuestion", new { id = ConnectionId });
        }

        public async Task<IActionResult> TestOnlineAsync(string SubjectName)
        {

            List<Class9QuestionSetViewModel> LsClass6Details = new List<Class9QuestionSetViewModel>();
            try
            {
                if (!string.IsNullOrEmpty(SubjectName))
                {
                    LsClass6Details = await _Class6Helper.FillClass6QuestionSetDetailsBySubjectName(LsClass6Details: LsClass6Details, SubjectName: SubjectName);
                }
            }
            catch(Exception ex)
            {
            }   
         

            return View(LsClass6Details);
        }

        public async Task<IActionResult> OnlineTest(int id, Test10DetailsViewModel test11)
        {

            int testa = 0;
            if (id == 0)
            {
                id = test11.ConnectionQuestion;
                testa = test11.TestId + 1;
            }

            try
            {
                if (test11.TestId != 0)
                {


                    TblClass6EnglisgTestFinalDetail finalResute = new TblClass6EnglisgTestFinalDetail();


                    finalResute.QuestionNo = test11.QuestionNo;

                    if (string.IsNullOrEmpty(test11.Answer) == false)
                    {
                        string[] Answer = test11.Answer.ToString().Split('-');
                        if (Answer.Length == 2)
                        {
                            if (Answer[0] == "A")
                            {
                                finalResute.AnswerA = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "B")
                            {
                                finalResute.AnswerB = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "C")
                            {
                                finalResute.AnswerC = Answer[1].ToString().Trim();
                            }
                            if (Answer[0] == "D")
                            {
                                finalResute.AnswerD = Answer[1].ToString().Trim();
                            }
                        }
                    }

                    if (String.IsNullOrEmpty(finalResute.AnswerA) == false)
                    {
                        if (finalResute.AnswerA == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerB) == false))
                    {
                        if (finalResute.AnswerB == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerC) == false))
                    {
                        if (finalResute.AnswerC == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }
                    else if ((String.IsNullOrEmpty(finalResute.AnswerD) == false))
                    {
                        if (finalResute.AnswerD == test11.CurrectAnswer)
                        {
                            finalResute.CurrectAnswer = test11.CurrectAnswer;
                        }
                    }

                    finalResute.ConnectedQuestion = test11.ConnectionQuestion;

                    var currentuser = User.Identity.Name;
                    if (string.IsNullOrEmpty(currentuser) == false)
                    {
                        finalResute.CurrentUser = currentuser;
                    }
                    else
                    {
                        finalResute.CurrentUser = "Na";
                    }


                    finalResute.TestQuestionId = test11.TestId;
                    finalResute.DatetimeStamp = DateTime.Now;

                    if (String.IsNullOrEmpty(finalResute.CurrentUser) == true)
                    {
                        finalResute.CurrentUser = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerA) == true)
                    {
                        finalResute.AnswerA = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerB) == true)
                    {
                        finalResute.AnswerB = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerC) == true)
                    {
                        finalResute.AnswerC = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.AnswerD) == true)
                    {
                        finalResute.AnswerD = "";
                    }
                    if (String.IsNullOrEmpty(finalResute.QuestionNo) == true)
                    {
                        finalResute.QuestionNo = "";
                    }

                    if (String.IsNullOrEmpty(finalResute.CurrectAnswer) == true)
                    {
                        finalResute.CurrectAnswer = "";
                    }

                    if (String.IsNullOrEmpty(finalResute.TestSerise) == true)
                    {
                        finalResute.TestSerise = "";
                    }

                    finalResute.Remark = "";
                    finalResute.Remark1 = "";
                    finalResute.Remark2 = "";
                    finalResute.Remark3 = "";
                    finalResute.Remark4 = "";

                    await _Class6Helper.SavetblClass6EnglisgTestFinalDetails(finalResute: finalResute);

                    id = test11.ConnectionQuestion;
                    testa = test11.TestId + 1;
                }

         

                if (String.IsNullOrEmpty(test11.FinalTest) == false)
                {

                    List<TblClass6EnglisgTestFinalDetail> LsClass6EnglisgTestFinalDetails = new List<TblClass6EnglisgTestFinalDetail>();

                    LsClass6EnglisgTestFinalDetails = await _Class6Helper.GetClass6EnglishTest20Details(LsClass6EnglisgTestFinalDetails: LsClass6EnglisgTestFinalDetails);




                    string TestIndexId = await _Class6Helper.SaveTestSeriesClass6Details(Class6TestSeriesDetails: test11);

quezemasterNew/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Test Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--card -->
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />


<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/quezemasterNew.styles.css" asp-append-version="true" />
<link href="~/css/sb-admin.css" rel="stylesheet" />
<link href="~/css/sb-admin.min.css" rel="stylesheet" />
<link href="~/fontawesome-free/css/all.css" rel="stylesheet" />
<link href="~/fontawesome-free/css/all.min.css" rel="stylesheet" />

<link href="~/css/fluent.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<style>
    a5:visited, a.ex5:link {
        text-decoration: none;
    }

    a.ex5:hover, a.ex5:active {
        text-decoration: underline;
    }
</style>
<script>
    function Go For Test() {
        alert("Comming Soon");
    }
</script>
<br />
<br />
<h3 class="text-dark text-center mt-5 fw-bold">Question Details</h3>
<div class="row mt-4">
    <div class="row">
        <div class="col-md-4">
            <div class="w3-panel w3-card">
                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">General Aptitude</h2>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="QuezIndex10Detail" asp-action="Index">UPP</a>

                </h5>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" onclick="Go For Test()">Data Interpretation</a>
                </h5>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" onclick="Go For Test()">Online Aptitude Test</a>
                </h5>
                <br />
            </div>
        </div>

        <div class="col-md-4">
            <div class="w3-panel w3-card">
                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">English</h2>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="TGTPGTLTEnglish" asp-action="TGTIndex">TGT</a>

                </h5>

                <h5 style="font-size:17px;color:darkslategray">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="TGTPGTLTEnglish" asp-action="PGTIndex">PGT</a>
                </h5>

                <h5 style="font-size:17px;color:darkslategray">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="TGTPGTLTEnglish" asp-action="LTIndex">LT</a>
                </h5>

                <br />
            </div>
        </div>

        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">English (BPSC)</h2>


                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="BPSCEnglish" asp-action="Index" asp-route-Subject="6To8">6 to 8</a>

                    <h5 style="font-size:17px;color:darkslategray">
                        <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                        <a class="ex5" asp-controller="BPSCEnglish" asp-action="Index" asp-route-Subject="9To10">9 to 10</a>

                    </h5>

                    <h5 style="font-size:17px;color:darkslategray">
                        <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                        <a class="ex5" asp-controller="BPSCEnglish" asp-action="Index" asp-route-Subject="11To12">11 to 12</a>

                    </h5>

                    <br />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">GK</h2>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" href="#" onclick="Go For Test()">BPSC</a>

                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" onclick="Go For Test()">UP SSC</a>
                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" href="#" onclick="Go For Test()">HR Interview</a>
                </h5>
                <br />
            </div>
        </div>
        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">Class 9th</h2>


                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="Class9" asp-action="Index" asp-route-Subject="Hindi">
                        Hindi
                    </a>

                </h5>
                <style>

                </style>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class9" asp-action="Index" asp-route-Subject="English">
                        English
                    </a>

                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class9" asp-action="Index" asp-route-Subject="Science">Science</a>
                </h5>
                <br />
            </div>
        </div>

        <div class="col-md-4">
            <div class="w3-panel w3-card">
                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">Class 10th</h2>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="CLass10" asp-action="Index" asp-route-Subject="Hindi">Hindi</a>
                </h5>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="CLass10" asp-action="Index" asp-route-Subject="English">English</a>
                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="CLass10" asp-action="Index" asp-route-Subject="Science">Science</a>
                </h5>
                <br />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">Class 11th</h2>


                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="Class11" asp-action="Index" asp-route-Subject="Hindi">Hindi</a>

                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class11" asp-action="Index" asp-route-Subject="English">English</a>

                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class11" asp-action="Index" asp-route-Subject="History">History</a>

                </h5>

            </div>
        </div>

        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">Class 12th</h2>
                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="Class12" asp-action="Index" asp-route-Subject="Hindi">Hindi</a>
                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class12" asp-action="Index" asp-route-Subject="English">English</a>
                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class12" asp-action="Index" asp-route-Subject="History">History</a>

                </h5>
            </div>
        </div>

        <div class="col-md-4">
            <div class="w3-panel w3-card">

                <h2 style="color:#4CBB17;font-size:23px;padding-top:18px;padding-left:5px">Academic</h2>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="Class6" asp-action="Index">Class 6 All Subject</a>

                </h5>


                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:22px" class="fa fa-angle-right" alt=""></i>
                    <a class="ex5" asp-controller="Class7" asp-action="Index">Class 7 All Subject</a>

                </h5>

                <h5 style="font-size:17px;color:black">
                    <i style="padding-left:7px;font-size:17px;color:black;padding:7px;padding-top:12px" class="fa fa-angle-right"></i>
                    <a class="ex5" asp-controller="Class8" asp-action="Index">Class 8 All Subject</a>
                </h5>
                <br />
            </div>
        </div>
    </div>


</div>
</div>

quezemasterNew/Views/Admin/SheAllTest.cshtml
@model IEnumerable<quezemasterNew.Models.ViewModel.Test.AllTestResultViewModel>

@{
    ViewData["Title"] = "SheAllTest";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="text-center pt-4 pb-3  fw-bold">All Test</h3>

<table class="table table-bordered">
    @{
        <thead>
            <tr>
                <th>
                    Sr.No
                </th>
                <th>
                    Name
                </th>
                <th>
                    Class
                </th>
                <th>
                    Test Name
                </th>

                <th>
                    Date
                </th>
                <th>
                    Mark
                </th>
            </tr>
        </thead>
        var i = 1;
        <tbody>
            @foreach (var item in Model.OrderByDescending(x=>x.Date))
            {
                <tr>
                    <td>
                        @Html.Label("" + i++.ToString())
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClassName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrectAnswer)/20
                    </td>

                </tr>
            }
        </tbody>
    }
</table>